const mongoose = require('mongoose');
const dataSchema = new mongoose.Schema({
    username: String,
    email:String,
    password: String,
    full_name: String,
  gender: String,
  contact_number: String,
  Google_map:String,
  address: String,
  languages_spoken: String,
  years_experience: String,
  certification: String,
  discription:String,
  profiledb:String,
  Idcheck:String,
  packagename:String,
  packid:String,
  mainabout:String,
  hotelabout:String,
  packhref:String,
  packplacename:String,
  packtimetrip:String,
  mainImages:String,
  hotelImage:String,
  focus:String,
  DPImage:String,
  mainimage1:String,
  mainimage2:String,
  mainimage3:String,
  hotelimage1:String,
  hotelimage2:String,
  hotelimage3:String,
  Height:String,
  usercomments:String,
  usercommentsemail:String,
  placename:String,
  placeabout:String,
  googlemaplocation:String,
  points:String,
  placeimage:String,
  totalRating:Number,
  totaluserRating:Number,
  Ratinguserid:String,

  
})
module.exports=dataSchema